defaults:
  - env: default
  - trajectory: edge_position
  - render: disabled
  - _self_

seed: 0

save:
  actions: true
  trajectory: true
  final_mesh: true

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true
  job_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        level: INFO
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        level: INFO
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers: [console, file]
